#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get user timeline if posible
    tweets = helpers.get_user_timeline(sys.argv[1].lstrip("@"), 50)
    
    if tweets == None:
        sys.exit('Error')
    
    #analize each tweet    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(tweet, "red"))
        else:
            print(colored(tweet, "yellow"))
            
if __name__ == "__main__":
    main()